'use client';

import React from 'react';
// import type { Metadata } from 'next';
import { Provider } from 'react-redux';
import { ApolloProvider } from '@apollo/client';
import { store } from '../store/index';
import '../styles/globals.scss';
import { client } from '../graphql/client';
import { Navbar } from '@/components/main-layout/navbar/navbar';
import { Footer } from '@/components/main-layout/footer/footer';
import css from './main-layout.module.scss';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>
          <Provider store={store}>
            <Navbar />
            <main className={css.main}> {children}</main>

            <Footer />
          </Provider>
        </ApolloProvider>
      </body>
    </html>
  );
}
